### ISSUE TITLE
Doesn't work with ConEmu64.exe

### ISSUE THREAD

**Issue by luckytea** [kiliwalk/sublime_cmd#2]
Sublime Text can't start ConEmu 64x.
Problem here:

```
 def open_conemu(self, dirname, title):
         command= "start conemu.exe /Single /Dir "+dirname+" /cmdlist cmd -new_console:t:\""+title+"\""
         os.system(command)
```

I don't know how to fix iot properly, but 

```
command = "start conemu.exe /Single /Dir "+dirname+" /cmdlist cmd -new_console:t:\""+title+"\""
command64 = "start conemu64.exe /Single /Dir "+dirname+" /cmdlist cmd -new_console:t:\""+title+"\""
         os.system(command) & os.system(command64)
```

It will show error, but still better than nothing.

**Comment by tianjianchn** [comment]
Hi, @LuckyTea . I'm currently using Mac, and so have long time not using st with this plugin. 
And I'm busy for current work, so I have no plan to change or upgrade this.
As a simple advice, If you'd like to use the 64-bit version, I think you can change the `conemu.exe` to `conemu32.exe` and `conemu64.exe` to `conemu.exe` so that the plugin will use the 64bit one
